### ISSUE TITLE
TODO´s

### ISSUE THREAD

**Issue by freyavs** [DEV21-G07/practica3#1]
### practica 3 vragen
- [x] hoe moet het menu eruit zien zoals de omgeving? "Este prototipo completará su contenido con un menú inicial (con opciones Jugar, Configurar y Salir, y decorado con ese mismo entorno natural del juego)"
- [x] is hud goed hoe hij is (wss enkel timer tonen als hij potion heeft genomen)
- [x] wat is kwaliteit bij optie configuratie
- [x] moet code verbeterd worden uit practica 1 - of bv enkel de organisatie etc
- [x] probleem met lighting build

### vorige practica vragen
- [x] "Tampoco están bien ordenados los actores en el nivel (no hay carpetas para organizarnos) y no hay una carpeta específica para guardar tus recursos en el proyecto. Aunque hay comentarios, se podrían añadir más y más sistemáticos." -> moet het in folders worden georganiseerd of ook rechts boven, waar kan ik nog meer commentaar zetten? gewoon langere zinnen?
- [x] "La organización del contenido y de los niveles es algo irregular. El uso de identificadores significativos para las variables y funciones, y los comentarios están bastante presentes."
- [x] vraag of hij toegang heeft tot github want sowieso wel "El profesor no tiene acceso pleno a la organización DEV21-GXX en GitHub. No se pueden ver los commits de todos los que pertenecen al grupo o no están equitativamente repartidos." en "No hay repositorio o yo no tengo puesto en enlace."
- [x] "La documentación del diseño y desarrollo en GitHub brilla es escasa." wat betekent dit
- [x] zeg da je pract2 hebt moeten verwijderen

### todo practica3
- [x] personaliseer level met naam enz
- [x] verplaats landscape material naar content!
- [x] herstructureer

### todo practica2
- [x] organiseer beter
- [x] meer en beter georganiseerde comments
